# Generated by Django 3.2.7 on 2021-09-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_qr', '0002_auto_20210905_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='contact_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='emergency_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
