# Generated by Django 3.2.7 on 2021-09-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_qr', '0003_auto_20210905_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='contact_no',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='emergency_no',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
