# Generated by Django 3.2.7 on 2021-09-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_qr', '0005_alter_userinfo_emergency_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='UserProfile',
        ),
    ]
