# Generated by Django 3.2.7 on 2021-09-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_qr', '0009_auto_20210908_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=100, null=True),
        ),
    ]
