# Generated by Django 3.2.7 on 2021-09-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_qr', '0012_userprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
